using System.Collections.Generic;

namespace SchoolManagement.Data.Constants
{
    public static class AccountsConst
    {
        public static List<string> accountNames = new List<string>() {
            "Advertisement & Publicity",
            "Conveyance Expenses",
            "Local Sales Tax",
            "Miscellaneous Expenses",
            "Office Equipments",
            "Office Maintenance Expenses",
            "Office Rent",
            "Customer Entertainment Expenses",
            "Depreciation A/c",
            "Earnest Money",
            "Excise Duty",
            "Freight & Forwarding Charges",
            "Furniture & Fixture",
            "Legal Expenses",
            "Plant & Machinery",
            "Tution Fees",
            "Registration Fees",
            "Late Fees",
            "Concession In Fees",
            "Old Balance A/c",
            "Prospectus Fee",
            "Postal Expenses",
            "Printing & Stationery",
            "Rounded Off",
            "Salary",
            "Salary & Bonus Payable",
            "Sales Promotion Expenses",
            "Staff Welfare Expenses",
            "TDS(Interest)",
            "TDS(Salary)",
            "Telephone Expenses",
            "Travelling Expenses",
            "Water & Electricity Expenses",
            "Discount",
            "VAT",
            "Cash",
            "Stock",
            "Profit & Loss",
            "Sales",
            "Purchase",
            "Replacement",
            "Edu.Cess on TDS",
            "Service Tax",
            "SHE Cess on Excise",
            "SHE Cess on Service Tax",
            "SHE Cess on TDS",
            "Surcharge on VAT",
            "TDS(Advertisement)",
            "TDS(Commission)",
            "TDS(Contractor)",
            "TDS(Rent)",
            "Notional VAT",
            "Income From Notional Vat",
            "Daami",
            "Labour",
            "Sewing Charges",
            "Misc.Charges",
            "Other Charges",
            "Mall Khata A/c",
            "Market Fees",
            "RDF",
            "Bank Charges",
            "Bad Debts Written Off",
            "Books & Periodicals",
            "Capital Equipments",
            "Central Sales Tax",
            "Commission on Sales",
            "Computers",
            "Stitching",
            "Bonus",
            "Development Tax",
            "Edu.Cess on Excise",
            "Edu.Cess on Service Tax",
            "Transport Charges",
            "Admission Fees",
            "Job Charges",
            "Interest Receivable A/c",
            "Interest Payable A/c",
            "Charity & Donations",
            "Sales VAT 5%",
            "Sales VAT 12.5%",
            "Sales Retail 5%",
            "Sales Retail 12.5%",
            "CST Sales",
            "Purchase Vat 5%",
            "Purchase Vat 12.5%",
            "Purchase Retail 5%",
            "Purchase Retail 12.5%",
            "CST Purchase",
            "C Form Sale",
            "C Form Purchase",
            "TOLL TAX",
            "DELIVERY CHARGES",
            "Admission Fee",
            "Exam Fee",
            "Sport Fee",
            "Tuition Fee"
        };

      
    }
}
