// <auto-generated />
namespace SchoolManagement.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FeeReceipts_Alter_Cols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeeReceipts_Alter_Cols));
        
        string IMigrationMetadata.Id
        {
            get { return "202103101349102_FeeReceipts_Alter_Cols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
