// <auto-generated />
namespace SchoolManagement.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20221125_Batches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20221125_Batches));
        
        string IMigrationMetadata.Id
        {
            get { return "202211250547574_20221125_Batches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
