// <auto-generated />
namespace SchoolManagement.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tbl_StaffAttendance4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tbl_StaffAttendance4));
        
        string IMigrationMetadata.Id
        {
            get { return "202203222008362_Tbl_StaffAttendance4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
